# Generated by Django 5.1.2 on 2024-10-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('interior', 'Interior'), ('exterior', 'Exterior')], max_length=10)),
                ('precio', models.FloatField()),
                ('marca', models.CharField(max_length=100)),
                ('resolucion', models.IntegerField()),
            ],
        ),
    ]
