# Generated by Django 5.1.2 on 2024-10-11 23:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camaras', '0002_camara_camara'),
    ]

    operations = [
        migrations.AddField(
            model_name='camara',
            name='angulo_de_vision',
            field=models.DecimalField(decimal_places=2, default=90.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camara',
            name='nombre',
            field=models.CharField(default='Camara', max_length=100),
        ),
        migrations.AlterField(
            model_name='camara',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='camara',
            name='resolucion',
            field=models.IntegerField(default=720),
        ),
    ]
