# Generated by Django 5.1.2 on 2024-10-11 23:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camaras', '0003_camara_angulo_de_vision_camara_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camara',
            name='angulo_de_vision',
            field=models.DecimalField(decimal_places=2, default=90.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)]),
        ),
    ]
