# Generated by Django 5.1.2 on 2024-10-13 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Camaras', '0004_alter_camara_angulo_de_vision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camara',
            old_name='angulo_de_vision',
            new_name='angulo_vision',
        ),
    ]
