# Generated by Django 5.1.3 on 2024-11-12 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Camaras', '0005_rename_angulo_de_vision_camara_angulo_vision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('camara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Camaras.camara')),
            ],
        ),
    ]
